version: "3.7"

networks:
  spendmanagement:
    external:
      name: spendmanagement-network

services:

    apigateway:
      container_name: spendmanagement_apigateway
      build:
        context: .
        dockerfile: Dockerfile
      image: spendmanagement_apigateway:${APP_VERSION}
      environment:
        - APP_VERSION=${APP_VERSION}
        - ASPNETCORE_ENVIRONMENT=Docker
      ports:
        - "8079:80"
      networks:
        - spendmanagement